// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type User struct {
	ID             string `json:"id"`
	Name           string `json:"name"`
	ProfilePicture string `json:"profilePicture"`
	Subscriber     int    `json:"subscriber"`
}

type NewUser struct {
	ID             string `json:"id"`
	Name           string `json:"name"`
	ProfilePicture string `json:"profilePicture"`
	Subscriber     int    `json:"subscriber"`
}
